[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "pysisyphus/version.py"

[tool.ruff]

[tool.ruff.lint]
# E741: ambiguous variable name
ignore = ["E741"]
extend-select = ["NPY201"]
preview = true
