name: Python application

on:
    push:
        paths-ignore:
            - "docs/**"
            - "examples/**"
            - "scripts/**"
            - "nix/**"
    workflow_dispatch:
    schedule:
        - cron: '0 */12 * * *'
jobs:
  buildNix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          extra_nix_config: access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v15
        with:
          name: pysisyphus
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-build nix/
      - run: nix-shell nix/ --run "echo OK"
